const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
let latestProject='';
async function loadComponents(q=''){const r=await fetch('/api/components?q='+encodeURIComponent(q));const d=await r.json();$('#componentsGrid').innerHTML=d.components.map(c=>`<div class="component"><b>${esc(c.name)}</b><span>${esc(c.category)} · ${esc(c.tags.join(', '))}</span><strong>₹${c.price.toLocaleString('en-IN')} est.</strong></div>`).join('')}
$('#search').addEventListener('input',e=>loadComponents(e.target.value));loadComponents();
$('#plan').onclick=async()=>{const btn=$('#plan');btn.disabled=true;btn.textContent='Building plan…';try{const r=await fetch('/api/plan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt:$('#prompt').value,budget:$('#budget').value})});const d=await r.json();latestProject=d.project;$('#result').classList.remove('hidden');$('#result').innerHTML=`<h3>${esc(d.project)}</h3><table><tr><th>Component</th><th>Qty</th><th>Estimate</th></tr>${d.items.map(i=>`<tr><td>${esc(i.name)}</td><td>${i.quantity}</td><td>₹${i.cost.toLocaleString('en-IN')}</td></tr>`).join('')}</table><p><b>Estimated total: ₹${d.total_estimate.toLocaleString('en-IN')}</b> ${d.budget?`· Budget: ₹${Number(d.budget).toLocaleString('en-IN')}`:''}</p><p>${d.within_budget?'✅ Within the stated budget.':'⚠️ Above the stated budget.'}</p><p><b>Builder notes:</b> ${d.alternatives.map(esc).join(' ')}</p>`}finally{btn.disabled=false;btn.textContent='Generate engineering plan →'}};
$('#availabilityBtn').onclick=async()=>{const q=$('#availQuery').value;const r=await fetch('/api/availability?q='+encodeURIComponent(q));const d=await r.json();$('#availabilityResult').classList.remove('hidden');$('#availabilityResult').textContent=JSON.stringify(d,null,2)};
$('#firmwareBtn').onclick=async()=>{const r=await fetch('/api/firmware',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({platform:$('#platform').value,project:latestProject||$('#prompt').value||'line-following robot'})});const d=await r.json();$('#firmwareOut').textContent=d.code};
$('#circuitBtn').onclick=async()=>{const r=await fetch('/api/circuit',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({project:latestProject||$('#prompt').value||'line-following robot'})});const svg=await r.text();$('#circuitOut').innerHTML=svg};
$('#cadBtn').onclick=async()=>{const r=await fetch('/api/cad',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({project:latestProject||$('#prompt').value||'robot chassis'})});const d=await r.json();$('#cadOut').textContent=d.code};
$('#simBtn').onclick=async()=>{const r=await fetch('/api/simulate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({project:latestProject||$('#prompt').value||'robot',duration:10})});const d=await r.json();const c=$('#simCanvas'),ctx=c.getContext('2d');ctx.clearRect(0,0,c.width,c.height);ctx.strokeStyle='#39b7ff';ctx.lineWidth=2;ctx.beginPath();const xs=d.trajectory.x,ys=d.trajectory.y;const minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys),sx=420/Math.max(0.001,maxX-minX),sy=180/Math.max(0.001,maxY-minY);xs.forEach((x,i)=>{const px=50+(x-minX)*sx,py=220-(ys[i]-minY)*sy;i?ctx.lineTo(px,py):ctx.moveTo(px,py)});ctx.stroke();ctx.fillStyle='#e7f4ff';ctx.fillText('2D kinematic path',12,20)};
async function auth(){const r=await fetch('/api/me');const d=await r.json();$('#login').classList.toggle('hidden',d.authenticated);$('#logout').classList.toggle('hidden',!d.authenticated);if(d.authenticated)$('#login').textContent=d.user.name||d.user.email}auth();$('#login').onclick=()=>location.href='/api/auth/google';$('#logout').onclick=async()=>{await fetch('/api/auth/logout',{method:'POST'});auth()};
